### ISSUE TITLE
bevy_sprite instead of bevy_ui, rework API?

### ISSUE THREAD

**Issue by johanhelsing** [SergioRibera/virtual_joystick#8]
Seems like a neat little project. It has a lot of stuff I want, but also quite a few things I'd like to change/add. I'm wondering whether you'd want PRs to fix this, or if it's better that I create my own fork.

**Is your feature request related to a problem? Please describe.**

- bevy_sprite instead of bevy_ui. Bevy ui is still not ready for use in my opinion, I'd rather have something that works with sprites or some modular mechanism for rendering.
- Resources or entities instead of events. Event's are kind of clunky to work with, it would be more convenient for me to be able to do something like `joystick: Res<VirtualJoystick>` and `translation.x += joystick.x() * speed`. More in line with how other bevy input APIs work.
- Optinal integration with leafwing input manager through feature flag.

**Additional context**
I need this functionality pretty soon.

Sorry, if this seems like critique, I guess it technically is, but I'm also really grateful that you took the time to contribute this to the community. Will probably save me some time ❤️

**Comment by SergioRibera** [comment]
But of course, you are really free to do whatever you like, I would prefer a contribution as it is also a project that I use a lot in my personal projects so all the features and changes you have in mind are super welcome to discuss them, maybe even help you to implement some of them.

Regarding the suggestions you gave

> bevy_sprite instead of bevy_ui. Bevy ui is still not ready for use in my opinion, I'd rather have something that works with sprites or some modular mechanism for rendering.

Could you tell me a little more about this please, I'm currently using the ui to render it because it needs the joystick to always overlap regardless of its depth, also the tools provided by Bevy to implement a custom UI as it is the case, is much more flexible than the sprite, even so as you mention there may be those who need it so based on features we could change this behavior, here I could use a super contribution. On the other hand can you tell me your particular case why you need it as a sprite?

> Resources or entities instead of events. Event's are kind of clunky to work with, it would be more convenient for me to be able to be able to do something like joystick: Res<VirtualJoystick> and translation.x += joystick.x() * speed. More in line with how other bevy input APIs work.

About this I might disagree, most of the inputs that Bevy handles are done through Events, this also helps a lot to not have jumps, because it works as a queue of accumulated messages, which allows to have updates by steps, but it would not be bad to have a Resource as you mention, if you feel like doing a PR, we could try it, for my part in my free time I will try to implement it and compare the results.

> Optinal integration with leafwing input manager through feature flag.

This if I had planned it but I did not have the time to review it calmly, it is definitely something I would like to include, again, I cordially invite you to contribute, it would be very nice to have such interesting contributions.

**Comment by johanhelsing** [comment]
If I had more time, I would probably contribute, but I only have a few days at most.

Most likely I'll fork and remove the features I don't need, and implement the ones I'm missing.

bevy_ui might be okay, I just don't use it for anything else, due to the insane amount of boilerplate it requires.
